-- Auto-generated by scripts/generate_coords_update_sql.py
BEGIN;

UPDATE peaks SET latitude=50.7775, longitude=15.5675, elevation_m=1510 WHERE slug='wielki-szyszak';
UPDATE peaks SET latitude=50.755, longitude=15.676389, elevation_m=1490 WHERE slug='smogornia';
UPDATE peaks SET latitude=50.1914, longitude=16.8153, elevation_m=1327 WHERE slug='maly-snieznik';
UPDATE peaks SET latitude=50.6525, longitude=15.741944, elevation_m=1300 WHERE slug='czarna-gora';
UPDATE peaks SET latitude=50.8911, longitude=15.3058 WHERE slug='stog-izerski';
UPDATE peaks SET latitude=50.845556, longitude=15.491389, elevation_m=1058 WHERE slug='wysoki-kamien';
UPDATE peaks SET latitude=50.2233, longitude=17.0117, elevation_m=1117 WHERE slug='postawna';
UPDATE peaks SET latitude=50.69015, longitude=16.31135, elevation_m=902 WHERE slug='jeleniec-orlickie';
UPDATE peaks SET latitude=50.642778, longitude=16.546389, elevation_m=964 WHERE slug='kalenica';
UPDATE peaks SET latitude=50.6717, longitude=16.2353, elevation_m=781 WHERE slug='sredniak-sowie';
UPDATE peaks SET latitude=50.702722, longitude=16.190222 WHERE slug='lesista-bystrzyckie';
UPDATE peaks SET latitude=51.03, longitude=21.1436 WHERE slug='trojak-zlote';
UPDATE peaks SET latitude=50.173333, longitude=30.103889, elevation_m=162 WHERE slug='borowa';
UPDATE peaks SET latitude=50.702722, longitude=16.190222 WHERE slug='lesista-wielka';
UPDATE peaks SET latitude=50.47226, longitude=16.31929, elevation_m=915 WHERE slug='skalniak';
UPDATE peaks SET latitude=50.4591, longitude=16.3467, elevation_m=849 WHERE slug='naroza';
UPDATE peaks SET latitude=49.199722, longitude=19.729444, elevation_m=2136 WHERE slug='trzy-kopy';
UPDATE peaks SET latitude=49.173611, longitude=19.741389, elevation_m=2184 WHERE slug='baraniec-kaczawskie';
UPDATE peaks SET latitude=51.0565, longitude=15.7654 WHERE slug='ostrzyca';
UPDATE peaks SET latitude=50.2567, longitude=17.4556 WHERE slug='srebrna-kopa';
UPDATE peaks SET latitude=49.21825, longitude=20.0286, elevation_m=2291 WHERE slug='kozi-wierch';
UPDATE peaks SET latitude=49.5812, longitude=19.4996, elevation_m=1515 WHERE slug='maly-babia-gora';
UPDATE peaks SET latitude=45.981111, longitude=14.704444, elevation_m=454 WHERE slug='polica';
UPDATE peaks SET latitude=49.085833, longitude=22.738889, elevation_m=1335 WHERE slug='krzemien';
UPDATE peaks SET latitude=49.258056, longitude=25.138889, elevation_m=400 WHERE slug='halicz';
UPDATE peaks SET latitude=49.54775, longitude=20.15718, elevation_m=1288 WHERE slug='jaworzyna-kamienicka';
UPDATE peaks SET latitude=49.5725, longitude=20.1762, elevation_m=1274 WHERE slug='kudlon';
UPDATE peaks SET latitude=49.4399, longitude=20.6103 WHERE slug='wielki-rogal';
UPDATE peaks SET latitude=49.4503, longitude=20.6567 WHERE slug='niemcowa';
UPDATE peaks SET latitude=49.7158, longitude=20.1785, elevation_m=1007 WHERE slug='snieznica';
UPDATE peaks SET latitude=53.133056, longitude=21.247222 WHERE slug='jastrzabica';
UPDATE peaks SET latitude=49.43635, longitude=21.1241, elevation_m=903 WHERE slug='ostry-wierch';
UPDATE peaks SET latitude=49.7106, longitude=18.3281 WHERE slug='leskowiec';
UPDATE peaks SET latitude=49.611389, longitude=19.010556, elevation_m=1220 WHERE slug='barania-gora';
UPDATE peaks SET latitude=49.73983, longitude=18.995274, elevation_m=1117 WHERE slug='klimczok';
UPDATE peaks SET latitude=49.4136, longitude=20.4144, elevation_m=982 WHERE slug='trzy-korony';
UPDATE peaks SET latitude=50.6702, longitude=16.4784, elevation_m=913 WHERE slug='sokolica';
UPDATE peaks SET latitude=50.837369, longitude=16.710386, elevation_m=573 WHERE slug='radunia';
UPDATE peaks SET latitude=54.224444, longitude=18.123611, elevation_m=329 WHERE slug='wiezyca';
UPDATE peaks SET latitude=50.860278, longitude=21.046944, elevation_m=594 WHERE slug='lisa-gora';

-- Rebuild geom for all peaks with coords
UPDATE peaks
SET geom = ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

COMMIT;
