-- Auto-generated by scripts/generate_nearby_coords_sql.py
-- Source: Wikidata API (wbsearchentities + wbgetentities), coords from P625
BEGIN;

-- Wielki Szyszak
UPDATE peaks SET latitude = 50.777500, longitude = 15.567500 WHERE slug = 'wielki-szyszak';

-- Smogornia
UPDATE peaks SET latitude = 50.755000, longitude = 15.676389 WHERE slug = 'smogornia';

-- Czarna Góra (Masyw Śnieżnika)
UPDATE peaks SET latitude = 50.251900, longitude = 16.804900 WHERE slug = 'czarna-gora';

-- Mały Śnieżnik
UPDATE peaks SET latitude = 50.191400, longitude = 16.815300 WHERE slug = 'maly-snieznik';

-- Stóg Izerski
UPDATE peaks SET latitude = 50.891700, longitude = 15.303900 WHERE slug = 'stog-izerski';

-- Wysoki Kamień
UPDATE peaks SET latitude = 50.845556, longitude = 15.491389 WHERE slug = 'wysoki-kamien';

-- Postawna
UPDATE peaks SET latitude = 50.223300, longitude = 17.011700 WHERE slug = 'postawna';

-- Iwinka
UPDATE peaks SET latitude = 50.239992, longitude = 16.981944 WHERE slug = 'iwinka';

-- Jeleniec
UPDATE peaks SET latitude = 53.268600, longitude = 18.588900 WHERE slug = 'jeleniec-orlickie';

-- Sasanka
UPDATE peaks SET latitude = 50.264400, longitude = 16.563300 WHERE slug = 'sasanka-orlickie';

-- Kalenica
UPDATE peaks SET latitude = 50.643333, longitude = 16.546667 WHERE slug = 'kalenica';

-- Średniak
UPDATE peaks SET latitude = 50.240777, longitude = 16.943836 WHERE slug = 'sredniak-sowie';

-- Czarna Góra
UPDATE peaks SET latitude = 49.369583, longitude = 20.123028 WHERE slug = 'czarna-gora-bystrzyckie';

-- Lesista Wielka
UPDATE peaks SET latitude = 50.702722, longitude = 16.190222 WHERE slug = 'lesista-bystrzyckie';

-- Okołek
UPDATE peaks SET latitude = 53.947400, longitude = 23.344400 WHERE slug = 'okolik';

-- Sokolik Wielki
UPDATE peaks SET latitude = 50.846100, longitude = 15.841600 WHERE slug = 'sokolik-wielki';

-- Trojak
UPDATE peaks SET latitude = 51.814806, longitude = 21.899444 WHERE slug = 'trojak-zlote';

-- Rudawiec
UPDATE peaks SET latitude = 52.212778, longitude = 23.394722 WHERE slug = 'rudawiec-zlote';

-- Lesista Wielka
UPDATE peaks SET latitude = 50.702722, longitude = 16.190222 WHERE slug = 'lesista-wielka';

-- Borowa
UPDATE peaks SET latitude = 49.384611, longitude = 37.633056 WHERE slug = 'borowa';

-- Narożnik
UPDATE peaks SET latitude = 50.459100, longitude = 16.346700 WHERE slug = 'naroza';

-- Skalniak
UPDATE peaks SET latitude = 50.471900, longitude = 16.321100 WHERE slug = 'skalniak';

-- Trzy Kopy
UPDATE peaks SET latitude = 49.199722, longitude = 19.729444 WHERE slug = 'trzy-kopy';

-- Dzikowiec Wielki
UPDATE peaks SET latitude = 50.723889, longitude = 16.205833 WHERE slug = 'dzikowiec';

-- Obryń
UPDATE peaks SET latitude = 53.562500, longitude = 26.355556 WHERE slug = 'obora-bardzkie';

-- Srebrna Góra
UPDATE peaks SET latitude = 50.576040, longitude = 16.659910 WHERE slug = 'srebrna-gora';

-- Baraniec
UPDATE peaks SET latitude = 52.777400, longitude = 20.462300 WHERE slug = 'baraniec-kaczawskie';

-- Ostrzyca Proboszczowicka
UPDATE peaks SET latitude = 51.056100, longitude = 15.763300 WHERE slug = 'ostrzyca';

-- Srebrna Kopa
UPDATE peaks SET latitude = 50.256700, longitude = 17.455600 WHERE slug = 'srebrna-kopa';

-- Pietrosz
UPDATE peaks SET latitude = 47.125000, longitude = 25.185833 WHERE slug = 'pietrosz';

-- Mięguszowiecki Szczyt Wielki
UPDATE peaks SET latitude = 49.187222, longitude = 20.060000 WHERE slug = 'mieguszowiecki-szczyt';

-- Kozi Wierch
UPDATE peaks SET latitude = 49.218300, longitude = 20.028600 WHERE slug = 'kozi-wierch';

-- Mała Babia Góra
UPDATE peaks SET latitude = 49.581200, longitude = 19.499600 WHERE slug = 'maly-babia-gora';

-- Polica
UPDATE peaks SET latitude = 45.981111, longitude = 14.704444 WHERE slug = 'polica';

-- Krzemień
UPDATE peaks SET latitude = 53.368333, longitude = 15.534167 WHERE slug = 'krzemien';

-- Halicz
UPDATE peaks SET latitude = 49.112778, longitude = 24.721667 WHERE slug = 'halicz';

-- Kudłoń
UPDATE peaks SET latitude = 49.572500, longitude = 20.176200 WHERE slug = 'kudlon';

-- Jaworzyna Kamienicka
UPDATE peaks SET latitude = 49.549600, longitude = 20.158800 WHERE slug = 'jaworzyna-kamienicka';

-- Wielki Rogacz
UPDATE peaks SET latitude = 49.439900, longitude = 20.610300 WHERE slug = 'wielki-rogal';

-- Niemcowa
UPDATE peaks SET latitude = 49.450300, longitude = 20.656700 WHERE slug = 'niemcowa';

-- Śnieżnica
UPDATE peaks SET latitude = 49.716700, longitude = 20.178100 WHERE slug = 'snieznica';

-- Kudłacze
UPDATE peaks SET latitude = 53.550000, longitude = 22.416700 WHERE slug = 'kudla-wyspowy';

-- Łyżka (Beskid Wyspowy)
UPDATE peaks SET latitude = 49.640300, longitude = 20.469400 WHERE slug = 'lakowa-wyspowy';

-- Jastrząbka
UPDATE peaks SET latitude = 53.133056, longitude = 21.247222 WHERE slug = 'jastrzabica';

-- Ostry Wierch
UPDATE peaks SET latitude = 49.439200, longitude = 21.123100 WHERE slug = 'ostry-wierch';

-- Rotunda
UPDATE peaks SET latitude = 51.110138, longitude = 17.044388 WHERE slug = 'rotunda';

-- Leskowiec
UPDATE peaks SET latitude = 49.710600, longitude = 18.328100 WHERE slug = 'leskowiec';

-- Góra Żar
UPDATE peaks SET latitude = 50.829300, longitude = 15.636100 WHERE slug = 'gora-zar';

-- Barania Góra
UPDATE peaks SET latitude = 49.611389, longitude = 19.010556 WHERE slug = 'barania-gora';

-- Klimczok
UPDATE peaks SET latitude = 49.739830, longitude = 18.995274 WHERE slug = 'klimczok';

-- Trzy Korony
UPDATE peaks SET latitude = 49.413600, longitude = 20.414400 WHERE slug = 'trzy-korony';

-- Sokolica
UPDATE peaks SET latitude = 54.208333, longitude = 20.966667 WHERE slug = 'sokolica';

-- Turnica
UPDATE peaks SET latitude = 49.608900, longitude = 22.376700 WHERE slug = 'turnica';

-- Kiczera
UPDATE peaks SET latitude = 55.935833, longitude = 110.099167 WHERE slug = 'kiczera';

-- Łysica
UPDATE peaks SET latitude = 50.900000, longitude = 20.900000 WHERE slug = 'lysica-skarpowa';

-- Łysa Góra
UPDATE peaks SET latitude = 48.276100, longitude = 16.333300 WHERE slug = 'lisa-gora';

-- Recompute geom for updated peaks
UPDATE peaks SET geom = ST_SetSRID(ST_MakePoint(longitude::double precision, latitude::double precision), 4326)::geography WHERE slug IN ('wielki-szyszak','smogornia','czarna-gora','maly-snieznik','stog-izerski','wysoki-kamien','postawna','iwinka','jeleniec-orlickie','sasanka-orlickie','kalenica','sredniak-sowie','czarna-gora-bystrzyckie','lesista-bystrzyckie','okolik','sokolik-wielki','trojak-zlote','rudawiec-zlote','lesista-wielka','borowa','naroza','skalniak','trzy-kopy','dzikowiec','obora-bardzkie','srebrna-gora','baraniec-kaczawskie','ostrzyca','srebrna-kopa','pietrosz','mieguszowiecki-szczyt','kozi-wierch','maly-babia-gora','polica','krzemien','halicz','kudlon','jaworzyna-kamienicka','wielki-rogal','niemcowa','snieznica','kudla-wyspowy','lakowa-wyspowy','jastrzabica','ostry-wierch','rotunda','leskowiec','gora-zar','barania-gora','klimczok','trzy-korony','sokolica','turnica','kiczera','lysica-skarpowa','lisa-gora');

COMMIT;