# scripts/generate_nearby_coords_sql.py
import json
import time
import requests

WIKIDATA_SPARQL = "https://query.wikidata.org/sparql"

# Twoje slugi z seed_nearby_peaks + nazwy PL (żeby Wikidata znalazła właściwy obiekt)
PEAKS = [
  ("wielki-szyszak", "Wielki Szyszak"),
  ("smogornia", "Smogornia"),
  ("czarna-gora", "Czarna Góra (Masyw Śnieżnika)"),
  ("maly-snieznik", "Mały Śnieżnik"),
  ("stog-izerski", "Stóg Izerski"),
  ("wysoki-kamien", "Wysoki Kamień"),
  ("postawna", "Postawna"),
  ("iwinka", "Iwinka"),
  ("jeleniec-orlickie", "Jeleniec"),
  ("sasanka-orlickie", "Sasanka"),
  ("kalenica", "Kalenica"),
  ("sredniak-sowie", "Średniak"),
  ("czarna-gora-bystrzyckie", "Czarna Góra"),
  ("lesista-bystrzyckie", "Lesista Wielka"),
  ("okolik", "Okołek"),
  ("sokolik-wielki", "Sokolik Wielki"),
  ("trojak-zlote", "Trojak"),
  ("rudawiec-zlote", "Rudawiec"),
  ("lesista-wielka", "Lesista Wielka"),
  ("borowa", "Borowa"),
  ("naroza", "Narożnik"),
  ("skalniak", "Skalniak"),
  ("trzy-kopy", "Trzy Kopy"),
  ("dzikowiec", "Dzikowiec Wielki"),
  ("obora-bardzkie", "Obryń"),
  ("srebrna-gora", "Srebrna Góra"),
  ("baraniec-kaczawskie", "Baraniec"),
  ("ostrzyca", "Ostrzyca Proboszczowicka"),
  ("srebrna-kopa", "Srebrna Kopa"),
  ("pietrosz", "Pietrosz"),
  ("mieguszowiecki-szczyt", "Mięguszowiecki Szczyt Wielki"),
  ("kozi-wierch", "Kozi Wierch"),
  ("maly-babia-gora", "Mała Babia Góra"),
  ("polica", "Polica"),
  ("krzemien", "Krzemień"),
  ("halicz", "Halicz"),
  ("kudlon", "Kudłoń"),
  ("jaworzyna-kamienicka", "Jaworzyna Kamienicka"),
  ("wielki-rogal", "Wielki Rogacz"),
  ("niemcowa", "Niemcowa"),
  ("snieznica", "Śnieżnica"),
  ("kudla-wyspowy", "Kudłacze"),
  ("lakowa-wyspowy", "Łyżka (Beskid Wyspowy)"),
  ("jastrzabica", "Jastrząbka"),
  ("ostry-wierch", "Ostry Wierch"),
  ("rotunda", "Rotunda"),
  ("leskowiec", "Leskowiec"),
  ("gora-zar", "Góra Żar"),
  ("barania-gora", "Barania Góra"),
  ("klimczok", "Klimczok"),
  ("trzy-korony", "Trzy Korony"),
  ("sokolica", "Sokolica"),
  ("turnica", "Turnica"),
  ("kiczera", "Kiczera"),
  ("lysica-skarpowa", "Łysica"),
  ("lisa-gora", "Łysa Góra"),
]

def sparql_coords(label_pl: str):
  # Bierzemy obiekt, który ma polską etykietę, jest górą/szczytem i ma współrzędne
  # Uwaga: SPARQL może zwrócić kilka wyników — bierzemy pierwszy najbardziej trafny.
  query = f"""
  SELECT ?item ?itemLabel ?coord WHERE {{
    ?item rdfs:label "{label_pl}"@pl.
    ?item wdt:P625 ?coord.
    OPTIONAL {{ ?item wdt:P31 ?instance. }}
    SERVICE wikibase:label {{ bd:serviceParam wikibase:language "pl,en". }}
  }}
  LIMIT 5
  """
  headers = {
    "Accept": "application/sparql-results+json",
    "User-Agent": "PeakGuide/1.0 (coords updater; contact: local)"
  }
  r = requests.get(WIKIDATA_SPARQL, params={"query": query}, headers=headers, timeout=30)
  r.raise_for_status()
  data = r.json()
  bindings = data.get("results", {}).get("bindings", [])
  if not bindings:
    return None

  # coord jest w formacie "Point(lon lat)"
  coord = bindings[0]["coord"]["value"]  # e.g. "Point(19.010444 49.611417)"
  inside = coord.replace("Point(", "").replace(")", "")
  lon_str, lat_str = inside.split(" ")
  return float(lat_str), float(lon_str)

def main():
  found = []
  missing = []

  for slug, label in PEAKS:
    try:
      coords = sparql_coords(label)
      if coords is None:
        missing.append((slug, label))
      else:
        lat, lon = coords
        found.append((slug, label, lat, lon))
      time.sleep(0.15)  # bądź miły dla endpointu
    except Exception as e:
      missing.append((slug, label))
      print(f"ERR {slug} {label}: {e}")

  # SQL
  lines = []
  lines.append("-- Auto-generated by scripts/generate_nearby_coords_sql.py")
  lines.append("BEGIN;")
  lines.append("")
  for slug, label, lat, lon in found:
    lines.append(f"-- {label}")
    lines.append(
      "UPDATE peaks SET "
      f"latitude = {lat:.6f}, longitude = {lon:.6f} "
      f"WHERE slug = '{slug}';"
    )
    lines.append("")

  if found:
    slugs_list = ",".join([f"'{s}'" for s, _, _, _ in found])
    lines.append("-- Recompute geom for updated peaks")
    lines.append(
      "UPDATE peaks SET geom = ST_SetSRID("
      "ST_MakePoint(longitude::double precision, latitude::double precision), 4326"
      ")::geography "
      f"WHERE slug IN ({slugs_list});"
    )
    lines.append("")

  lines.append("COMMIT;")
  out = "\n".join(lines)

  with open("nearby_coords_update.sql", "w", encoding="utf-8") as f:
    f.write(out)

  print(f"✅ Wrote nearby_coords_update.sql with {len(found)} updates")
  if missing:
    print(f"⚠ Missing ({len(missing)}):")
    for slug, label in missing:
      print(f"  - {slug}: {label}")

if __name__ == "__main__":
  main()
