# scripts/generate_nearby_coords_sql.py
# Generates nearby_coords_update.sql by fetching real coords from Wikidata API (no SPARQL).
# Run:
#   python scripts/generate_nearby_coords_sql.py

import time
import requests

WIKIDATA_API = "https://www.wikidata.org/w/api.php"

HEADERS = {
    "User-Agent": "PeakGuide/1.0 (coords updater; local)",
}

# slug -> label (human readable) used for search
PEAKS = [
    ("wielki-szyszak", "Wielki Szyszak"),
    ("smogornia", "Smogornia"),
    ("czarna-gora", "Czarna Góra (Masyw Śnieżnika)"),
    ("maly-snieznik", "Mały Śnieżnik"),
    ("stog-izerski", "Stóg Izerski"),
    ("wysoki-kamien", "Wysoki Kamień"),
    ("postawna", "Postawna"),
    ("iwinka", "Iwinka"),
    ("jeleniec-orlickie", "Jeleniec"),
    ("sasanka-orlickie", "Sasanka"),
    ("kalenica", "Kalenica"),
    ("sredniak-sowie", "Średniak"),
    ("czarna-gora-bystrzyckie", "Czarna Góra"),
    ("lesista-bystrzyckie", "Lesista Wielka"),
    ("okolik", "Okołek"),
    ("sokolik-wielki", "Sokolik Wielki"),
    ("trojak-zlote", "Trojak"),
    ("rudawiec-zlote", "Rudawiec"),
    ("lesista-wielka", "Lesista Wielka"),
    ("borowa", "Borowa"),
    ("naroza", "Narożnik"),
    ("skalniak", "Skalniak"),
    ("trzy-kopy", "Trzy Kopy"),
    ("dzikowiec", "Dzikowiec Wielki"),
    ("obora-bardzkie", "Obryń"),
    ("srebrna-gora", "Srebrna Góra"),
    ("baraniec-kaczawskie", "Baraniec"),
    ("ostrzyca", "Ostrzyca Proboszczowicka"),
    ("srebrna-kopa", "Srebrna Kopa"),
    ("pietrosz", "Pietrosz"),
    ("mieguszowiecki-szczyt", "Mięguszowiecki Szczyt Wielki"),
    ("kozi-wierch", "Kozi Wierch"),
    ("maly-babia-gora", "Mała Babia Góra"),
    ("polica", "Polica"),
    ("krzemien", "Krzemień"),
    ("halicz", "Halicz"),
    ("kudlon", "Kudłoń"),
    ("jaworzyna-kamienicka", "Jaworzyna Kamienicka"),
    ("wielki-rogal", "Wielki Rogacz"),
    ("niemcowa", "Niemcowa"),
    ("snieznica", "Śnieżnica"),
    ("kudla-wyspowy", "Kudłacze"),
    ("lakowa-wyspowy", "Łyżka (Beskid Wyspowy)"),
    ("jastrzabica", "Jastrząbka"),
    ("ostry-wierch", "Ostry Wierch"),
    ("rotunda", "Rotunda"),
    ("leskowiec", "Leskowiec"),
    ("gora-zar", "Góra Żar"),
    ("barania-gora", "Barania Góra"),
    ("klimczok", "Klimczok"),
    ("trzy-korony", "Trzy Korony"),
    ("sokolica", "Sokolica"),
    ("turnica", "Turnica"),
    ("kiczera", "Kiczera"),
    ("lysica-skarpowa", "Łysica"),
    ("lisa-gora", "Łysa Góra"),
]

OVERRIDES = {
    "sokolik-wielki": (50.8461, 15.8416),
}


# ---- Wikidata helpers (NO SPARQL) ----

def _get(url, params, timeout=25, retries=2, backoff=0.6):
    last_err = None
    for i in range(retries + 1):
        try:
            r = requests.get(url, params=params, headers=HEADERS, timeout=timeout)
            r.raise_for_status()
            return r
        except Exception as e:
            last_err = e
            if i < retries:
                time.sleep(backoff * (2 ** i))
            else:
                raise last_err

def wikidata_search(query: str, lang: str):
    params = {
        "action": "wbsearchentities",
        "format": "json",
        "language": lang,
        "uselang": lang,
        "type": "item",
        "search": query,
        "limit": 10,
    }
    r = _get(WIKIDATA_API, params=params)
    return r.json().get("search", [])

def wikidata_get_entities(qids):
    if not qids:
        return {}
    params = {
        "action": "wbgetentities",
        "format": "json",
        "ids": "|".join(qids),
        "props": "claims",
    }
    r = _get(WIKIDATA_API, params=params)
    return r.json().get("entities", {})

def coords_from_entity(entity):
    # P625 = coordinate location
    claims = entity.get("claims", {})
    p625 = claims.get("P625")
    if not p625:
        return None

    mainsnak = p625[0].get("mainsnak", {})
    datavalue = mainsnak.get("datavalue", {})
    value = datavalue.get("value")
    if not value:
        return None

    lat = value.get("latitude")
    lon = value.get("longitude")
    if lat is None or lon is None:
        return None

    return float(lat), float(lon)

def wikidata_coords_by_search(label: str):
    # Try PL first, then EN fallback
    results = wikidata_search(label, "pl")
    if not results:
        results = wikidata_search(label, "en")
    if not results:
        return None

    # Pull entities for top results and pick first that has coords
    qids = [r.get("id") for r in results[:10] if r.get("id")]
    entities = wikidata_get_entities(qids)

    for qid in qids:
        ent = entities.get(qid)
        if not ent:
            continue
        coords = coords_from_entity(ent)
        if coords:
            return coords

    return None

# ---- SQL writer ----

def write_sql(found, out_path="nearby_coords_update.sql"):
    lines = []
    lines.append("-- Auto-generated by scripts/generate_nearby_coords_sql.py")
    lines.append("-- Source: Wikidata API (wbsearchentities + wbgetentities), coords from P625")
    lines.append("BEGIN;")
    lines.append("")

    for slug, label, lat, lon in found:
        lines.append(f"-- {label}")
        lines.append(
            "UPDATE peaks SET "
            f"latitude = {lat:.6f}, longitude = {lon:.6f} "
            f"WHERE slug = '{slug}';"
        )
        lines.append("")

    if found:
        slugs_list = ",".join([f"'{s}'" for s, _, _, _ in found])
        lines.append("-- Recompute geom for updated peaks")
        lines.append(
            "UPDATE peaks SET geom = ST_SetSRID("
            "ST_MakePoint(longitude::double precision, latitude::double precision), 4326"
            ")::geography "
            f"WHERE slug IN ({slugs_list});"
        )
        lines.append("")

    lines.append("COMMIT;")
    out = "\n".join(lines)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(out)

def main():
    found = []
    missing = []

    for slug, label in PEAKS:
        try:
            coords = OVERRIDES.get(slug) or wikidata_coords_by_search(label)

            if coords is None:
                missing.append((slug, label))
            else:
                lat, lon = coords
                found.append((slug, label, lat, lon))
            time.sleep(0.12)  # be nice to API
        except Exception as e:
            print(f"ERR {slug} {label}: {e}")
            missing.append((slug, label))

    write_sql(found)

    print(f"✅ Wrote nearby_coords_update.sql with {len(found)} updates")
    if missing:
        print(f"⚠ Missing ({len(missing)}):")
        for slug, label in missing:
            print(f"  - {slug}: {label}")

if __name__ == "__main__":
    main()
