-- Add countries and regions without breaking existing Polish mountain data.

begin;

create table public.countries (
	id bigint generated by default as identity primary key,
	code text not null unique,
	slug text not null unique,
	flag_emoji text,
	cover_image_url text,
	active boolean not null default true,
	sort_order integer not null default 0,
	created_at timestamptz not null default now()
);

create table public.countries_i18n (
	country_id bigint not null references public.countries(id) on delete cascade,
	lang varchar(8) not null references public.languages(code) on update cascade,
	name text not null,
	short_description text,
	description text,
	seo_title text,
	seo_description text,
	primary key (country_id, lang)
);

create table public.regions (
	id bigint generated by default as identity primary key,
	country_id bigint not null references public.countries(id) on delete cascade,
	slug text not null,
	cover_image_url text,
	active boolean not null default true,
	sort_order integer not null default 0,
	created_at timestamptz not null default now(),
	unique (country_id, slug)
);

create table public.regions_i18n (
	region_id bigint not null references public.regions(id) on delete cascade,
	lang varchar(8) not null references public.languages(code) on update cascade,
	name text not null,
	description text,
	seo_title text,
	seo_description text,
	primary key (region_id, lang)
);

alter table public.mountain_ranges
	add column country_id bigint references public.countries(id),
	add column region_id bigint references public.regions(id) on delete set null;

create index idx_regions_country_id on public.regions(country_id);
create index idx_mountain_ranges_country_id on public.mountain_ranges(country_id);
create index idx_mountain_ranges_region_id on public.mountain_ranges(region_id);

insert into public.countries (code, slug, flag_emoji, active, sort_order)
values ('PL', 'poland', '🇵🇱', true, 10);

insert into public.countries_i18n (
	country_id, lang, name, short_description, description, seo_title, seo_description
)
select
	c.id,
	translations.lang,
	translations.name,
	translations.short_description,
	translations.description,
	translations.seo_title,
	translations.seo_description
from public.countries c
cross join (
	values
		('pl', 'Polska', 'Odkrywaj polskie góry i ich najwyższe szczyty.', 'Przewodnik po pasmach, szczytach i górskich wyzwaniach w Polsce.', 'Góry w Polsce — szczyty, pasma i trasy | PeakGuide', 'Odkrywaj polskie góry: szczyty, pasma, mapy, trasy i praktyczne informacje.'),
		('en', 'Poland', 'Discover Poland''s mountains and highest peaks.', 'A guide to mountain ranges, peaks and hiking challenges in Poland.', 'Mountains in Poland — peaks, ranges and routes | PeakGuide', 'Discover Polish mountains, peaks, ranges, maps, routes and practical information.'),
		('ua', 'Польща', 'Відкривайте гори Польщі та їхні найвищі вершини.', 'Путівник гірськими хребтами, вершинами та маршрутами Польщі.', 'Гори Польщі — вершини, хребти та маршрути | PeakGuide', 'Відкривайте польські гори, вершини, карти, маршрути та практичну інформацію.'),
		('zh', '波兰', '探索波兰山脉及其最高峰。', '波兰山脉、山峰和徒步挑战指南。', '波兰山脉、山峰与路线 | PeakGuide', '探索波兰山脉、山峰、地图、路线和实用信息。')
) as translations(lang, name, short_description, description, seo_title, seo_description)
where c.code = 'PL'
	and exists (select 1 from public.languages l where l.code = translations.lang);

update public.mountain_ranges
set country_id = (select id from public.countries where code = 'PL')
where country_id is null;

alter table public.mountain_ranges
	alter column country_id set not null;

alter table public.countries enable row level security;
alter table public.countries_i18n enable row level security;
alter table public.regions enable row level security;
alter table public.regions_i18n enable row level security;

create policy "countries_public_read_active"
on public.countries for select
to anon, authenticated
using (active is true);

create policy "countries_i18n_public_read_active"
on public.countries_i18n for select
to anon, authenticated
using (
	exists (
		select 1 from public.countries
		where countries.id = countries_i18n.country_id and countries.active is true
	)
);

create policy "regions_public_read_active"
on public.regions for select
to anon, authenticated
using (active is true);

create policy "regions_i18n_public_read_active"
on public.regions_i18n for select
to anon, authenticated
using (
	exists (
		select 1 from public.regions
		where regions.id = regions_i18n.region_id and regions.active is true
	)
);

create policy "countries_admin_all"
on public.countries for all
to authenticated
using ((select public.is_peakguide_admin()))
with check ((select public.is_peakguide_admin()));

create policy "countries_i18n_admin_all"
on public.countries_i18n for all
to authenticated
using ((select public.is_peakguide_admin()))
with check ((select public.is_peakguide_admin()));

create policy "regions_admin_all"
on public.regions for all
to authenticated
using ((select public.is_peakguide_admin()))
with check ((select public.is_peakguide_admin()));

create policy "regions_i18n_admin_all"
on public.regions_i18n for all
to authenticated
using ((select public.is_peakguide_admin()))
with check ((select public.is_peakguide_admin()));

grant select on public.countries, public.countries_i18n,
	public.regions, public.regions_i18n to anon, authenticated;

grant insert, update, delete on public.countries, public.countries_i18n,
	public.regions, public.regions_i18n to authenticated;

grant usage, select on all sequences in schema public to authenticated;

commit;
